### ISSUE TITLE
V1 launch checklist

### ISSUE THREAD

**Issue by zihaoccc** [HexlinkOfficial/Hexlink-Web#58]
- [ ] Smart Contract Deployment
   - [ ] Admin
      - [ ] GnosisSafe
      - [ ] TimeLock
   - [ ] Hexlink
      - [ ] Impl/Proxy
   - [ ] Oracle
      - [ ] Registry/Email/Twitter
   - [ ] Account
      - [ ] Beacon/Proxy/Implementation
   - [ ] ERC20 Red Packet
      - [ ] Impl/Proxy
   - [ ] ERC721 Token Factory
      - [ ] ERC721 Beacon/Proxy/Implementation
   - [ ] Swap
- [ ]  Sender Pool Setup
- [ ] Tune gas cost
   - [ ] Smart contract
   - [ ] Frontend
- [ ] Service Deployment
   - [ ] Frontend
   - [ ] Firebase functions
   - [ ] Hasura
   - [ ] Google Cloud SQL
   - [ ] Transaction service
   - [ ] Redis
   - [ ] Google Signing Service
   - [ ] Sendgrid
   - [ ] Alchemy/Infura
   - [ ] Doppler
- [ ] Test NFT Use Case
- [ ] Mobile Test
